### ISSUE TITLE
Which type of TVs does support this adapter?

### ISSUE THREAD

**Issue by GermanBluefox** [ldittmar81/ioBroker.sony-bravia#1]
Max be extend Readme with thus Info?

**Comment by ldittmar81** [comment]
Hmm... Sony Bravia... 😛 . I don't know because I don't have a Sony TV. I asked the tester and I'm waiting for the answer.

**Comment by GermanBluefox** [comment]
Ok. But as far as I know only Android TVs, isn't it?

2017-09-18 0:38 GMT+02:00 ldittmar <notifications@github.com>:

**Comment by ldittmar81** [comment]
Yes... only Android TV but I don't know if all Androids or only some.

**Comment by ldittmar81** [comment]
Bezeichnung auf "Sony Bravia Android Smart-TV" geändert undals Beispiel den KD-65X8507C hinzugefügt.
