### ISSUE TITLE
Only node 6 supported? constructor of ping is reason

### ISSUE THREAD

**Issue by Apollon77** [ldittmar81/ioBroker.sony-bravia#2]
see tests :-)

**Comment by ldittmar81** [comment]
Ja... ich habe es schon gesehen. Liegt aber nicht am Ping, sondern an der Bravia-Bibliothek. Da steht:

`constructor(host, port = 80, psk = '0000', timeout = 5000) {`

Und Node 4 unterstützt leider nicht diese Art von Vorbelegung. Ich werde also die Bibliothek kopieren und Node 4 kompatibel mitliefern müssen.

**Comment by Apollon77** [comment]
Oder ein Issue bei der Bibliothek aufmachen? Wenn das das einzige ist sollten die vllt mitspielen, oder !? Besser als kopieren oder forken

**Comment by ldittmar81** [comment]
Ich habe es erstmal lokal geändert und den Entwickler angeschrieben. Wenn er sich meldet bzw. den Code entsprechend ändern will, benutze ich wieder die Bibiothek. Jetzt geht es mit Node.js ab 4.x

**Comment by Apollon77** [comment]
cool
